### Get extended block
GET http://localhost:3000/extended-block/8403326
Accept: application/json

### Process the block
POST http://localhost:3000/block
Content-Type: application/json

{
  "id": 8403326
}

###
