service: daoscan
app: daoscan
org: ukstv

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  region: 'us-east-1'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  scraping-block:
    handler: functions/scraping.block
    environment:
      INFURA_PROJECT_ID: '7e19ece913ca433cadb164942a0b3e2e'
    events:
      - http:
          path: block
          method: post
          cors: true

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource:
      - "Fn::GetAtt": [ OrganisationsTable, Arn ]

resources:
  - ${file(resources/dynamodb.yml)}
