Resources:
  OrganisationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-organisations
      AttributeDefinitions:
        - AttributeName: address
          AttributeType: S
      KeySchema:
        - AttributeName: address
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
