Resources:
  OrganisationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-organisations
      AttributeDefinitions:
        - AttributeName: address
          AttributeType: S
      KeySchema:
        - AttributeName: address
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-applications
      AttributeDefinitions:
        - AttributeName: organisationAddress
          AttributeType: S
        - AttributeName: appId
          AttributeType: S
      KeySchema:
        - AttributeName: organisationAddress
          KeyType: HASH
        - AttributeName: appId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  ParticipantsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-participants
      AttributeDefinitions:
        - AttributeName: organisationAddress
          AttributeType: S
        - AttributeName: participantAddress
          AttributeType: S
      KeySchema:
        - AttributeName: organisationAddress
          KeyType: HASH
        - AttributeName: participantAddress
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
