---
Resources:
  ScrapingQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: ${self:custom.stage}-scraping-queue
      VisibilityTimeout: 300
  BlocksQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: ${self:custom.stage}-blocks-queue
      VisibilityTimeout: 300
