export enum ENV {
  PARTICIPANTS_TABLE = "PARTICIPANTS_TABLE",
  BLOCKS_SQS_URL = "BLOCKS_SQS_URL",
  SCRAPING_SQS_URL = "SCRAPING_SQS_URL",
  APPLICATIONS_TABLE = "APPLICATIONS_TABLE",
  APPLICATIONS_PER_ADDRESS_INDEX = "APPLICATIONS_PER_ADDRESS_INDEX",
  BLOCKS_TABLE = "BLOCKS_TABLE",
  ORGANISATIONS_TABLE = "ORGANISATIONS_TABLE",
  ETHEREUM_RPC = "ETHEREUM_RPC",
  PARTICIPANTS_INDEX = "PARTICIPANTS_INDEX",
  READ_DATABASE_URL = "READ_DATABASE_URL",
  WRITE_DATABASE_URL = "WRITE_DATABASE_URL",
  UTIL_SECRET = "UTIL_SECRET"
}
