export enum SCRAPING_EVENT_KIND {
  ORGANISATION_CREATED = "ORGANISATION_CREATED",
  APP_INSTALLED = "APP_INSTALLED",
  SHARE_TRANSFER = "SHARE_TRANSFER",
  ADD_DELEGATE = "ADD_DELEGATE",
  SET_ORGANISATION_NAME = "SET_ORGANISATION_NAME",
  SUBMIT_PROPOSAL = "SUBMIT_PROPOSAL",
  SUBMIT_VOTE = "SUBMIT_VOTE",
  PROCESS_PROPOSAL = "PROCESS_PROPOSAL"
}
